name: CI/CD Pipeline
&nbsp;
&nbsp;

on:
  push:
    branches:
      - main
&nbsp;
&nbsp;

jobs:
  build:
    runs-on: ubuntu-latest
&nbsp;
&nbsp;

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
&nbsp;
&nbsp;

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
&nbsp;
&nbsp;

      - name: Install dependencies
        run: npm install
&nbsp;
&nbsp;

      - name: Run tests
        run: npm test
&nbsp;
&nbsp;

      - name: Build application
        run: npm run build
&nbsp;
&nbsp;

      - name: Deploy to AWS
        run: |
          aws s3 sync ./build s3://your-bucket-name
