name: CI/CD Pipeline
&nbsp;
&nbsp;

on:
  push:
    branches:
      - main   # Change to your default branch if different
&nbsp;
&nbsp;

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
&nbsp;
&nbsp;

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
&nbsp;
&nbsp;

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # required for npm tools
&nbsp;
&nbsp;

    - name: Install HTML validator
      run: npm install -g html5validator
&nbsp;
&nbsp;

    - name: Validate HTML
      run: html5validator --root . --ignore ssi
&nbsp;
&nbsp;

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
&nbsp;
&nbsp;
